package update

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"net/http"
	"net/url"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"time"
)

// ReleaseRepo is the repository that publishes WxTap builds: the source
// repository itself, now that it is public.
//
// Its release assets must be anonymously downloadable for the update chain to
// work for anyone but this machine's owner: a private repository requires a
// token, and a token shipped inside the client is a token every user can read
// out of it. Publishing from the source repository keeps one address for the
// code, the issues, the releases and this manifest.
const ReleaseRepo = "langbyyi/wxtap"

// ManifestURLs lists the release manifest in fallback order. Assets carry
// their own source list, so adding a mirror for the payloads — including a
// domestic-hosted one — is done by editing the published document, with no new
// client build.
var ManifestURLs = []string{
	"https://raw.githubusercontent.com/" + ReleaseRepo + "/main/latest.json",
}

// maxManifestBytes caps the manifest document. It is a few hundred bytes in
// practice, and never a reason to let a remote host decide our allocation.
const maxManifestBytes = 64 << 10

// maxAssetBytes caps one update archive. The payloads compress to roughly 60MB
// in total; the cap stops a hostile manifest from requesting an unbounded
// download rather than bounding a legitimate one.
const maxAssetBytes = 200 << 20

// manifestTimeout bounds the manifest fetch. It is a small document, so this
// is generous.
const manifestTimeout = 20 * time.Second

// PlatformKey names this build's payload inside a manifest: the GOOS-GOARCH
// pair. Using the platform rather than a product-specific name keeps the
// document from having to know anything about WxTap beyond where it runs.
func PlatformKey() string {
	return runtime.GOOS + "-" + runtime.GOARCH
}

// Asset is one downloadable part of a release. A release is split because the
// distribution host caps a single attachment; every part extracts into the
// same staging root.
type Asset struct {
	Name   string   `json:"name"`
	Size   int64    `json:"size"`
	SHA256 string   `json:"sha256"`
	URLs   []string `json:"urls"`
}

// Payload is one platform's download set. It is an object rather than a bare
// array so the contract can gain fields without another breaking change — the
// schema is compiled into every shipped client, so changing it strands whoever
// is already out there.
type Payload struct {
	Assets []Asset `json:"assets"`
}

// Manifest is the published release document: the single source of truth for
// both "is there a newer version" and "where do its bytes come from". Reading
// one document for both answers removes the drift that a split between an OSS
// version file and a GitHub release allowed.
//
// Exactly one of Platforms and Assets is set:
//
//   - Platforms: a multi-platform release, keyed by PlatformKey.
//   - Assets: the single-payload form, used by a release that targets one
//     platform only (and by anything published before Platforms existed).
//
// Every platform entry is validated, not just the one this build will use: a
// manifest is one document generated by one script, so a malformed entry means
// the document is wrong, and reporting it beats shipping a release that is
// silently unusable on the platform it was meant for. After normalize, Assets
// always holds the running platform's payload and Platforms is cleared, so
// nothing downstream has to think about platforms at all.
type Manifest struct {
	Version   string             `json:"version"`
	Notes     string             `json:"notes"`
	Platforms map[string]Payload `json:"platforms,omitempty"`
	Assets    []Asset            `json:"assets,omitempty"`
}

// TotalSize is the download size of every asset, for display before the user
// commits to the transfer.
func (m Manifest) TotalSize() int64 {
	var total int64
	for _, asset := range m.Assets {
		total += asset.Size
	}
	return total
}

// FetchManifest returns the first manifest that resolves and validates.
// Sources are tried in order so a host that is unreachable from one network
// does not take the whole update path down with it.
func FetchManifest(ctx context.Context, urls []string) (Manifest, error) {
	if len(urls) == 0 {
		return Manifest{}, errors.New("没有配置更新源")
	}
	client := &http.Client{Timeout: manifestTimeout}
	var failures []error
	for _, source := range urls {
		manifest, err := fetchManifestFrom(ctx, client, source)
		if err != nil {
			failures = append(failures, fmt.Errorf("%s: %w", source, err))
			continue
		}
		return manifest, nil
	}
	return Manifest{}, fmt.Errorf("更新源全部失败: %w", errors.Join(failures...))
}

func fetchManifestFrom(ctx context.Context, client *http.Client, source string) (Manifest, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, source, nil)
	if err != nil {
		return Manifest{}, err
	}
	request.Header.Set("User-Agent", "WxTap")
	response, err := client.Do(request)
	if err != nil {
		return Manifest{}, err
	}
	defer func() { _ = response.Body.Close() }()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return Manifest{}, fmt.Errorf("HTTP %d", response.StatusCode)
	}
	body, err := readCappedBody(response.Body, maxManifestBytes)
	if err != nil {
		return Manifest{}, err
	}
	var manifest Manifest
	if err := json.Unmarshal(body, &manifest); err != nil {
		return Manifest{}, fmt.Errorf("清单不是合法 JSON: %w", err)
	}
	if err := manifest.normalize(); err != nil {
		return Manifest{}, err
	}
	return manifest, nil
}

// normalize validates the document, canonicalises the digests, and resolves the
// running platform's payload into Assets. After it returns, callers see exactly
// one payload — the one this build will download — with no platform dimension
// left to think about.
func (m *Manifest) normalize() error {
	m.Version = strings.TrimSpace(m.Version)
	if m.Version == "" {
		return errors.New("清单缺少版本号")
	}
	if !isPlainFileName(m.Version) {
		return fmt.Errorf("清单版本号不能作目录名: %q", m.Version)
	}
	assets, err := m.resolveAssets(PlatformKey())
	if err != nil {
		return err
	}
	m.Assets = assets
	m.Platforms = nil
	return nil
}

// resolveAssets returns platform's payload. Every entry in the document is
// validated on the way past, not just the requested one: see the note on
// Manifest for why a mistake in another platform is worth reporting here.
func (m *Manifest) resolveAssets(platform string) ([]Asset, error) {
	if len(m.Platforms) != 0 && len(m.Assets) != 0 {
		return nil, errors.New("清单同时给出了 platforms 与 assets，只能取其一")
	}
	if len(m.Platforms) == 0 {
		if len(m.Assets) == 0 {
			return nil, fmt.Errorf("清单 %s 没有可下载的分片", m.Version)
		}
		if err := canonicalizeAssets(m.Assets); err != nil {
			return nil, err
		}
		return m.Assets, nil
	}
	keys := slices.Sorted(maps.Keys(m.Platforms))
	for _, key := range keys {
		payload := m.Platforms[key]
		if len(payload.Assets) == 0 {
			return nil, fmt.Errorf("清单 %s 的 %s 平台没有分片", m.Version, key)
		}
		// canonicalizeAssets edits in place, and Payload's slice shares its
		// backing array with the map entry, so the digests stay canonicalised.
		if err := canonicalizeAssets(payload.Assets); err != nil {
			return nil, fmt.Errorf("平台 %s: %w", key, err)
		}
	}
	payload, ok := m.Platforms[platform]
	if !ok {
		return nil, fmt.Errorf("清单 %s 没有 %s 的构建，只有 %s", m.Version, platform, strings.Join(keys, ", "))
	}
	return payload.Assets, nil
}

// canonicalizeAssets checks one payload's assets and lower-cases their digests.
// The manifest is remote input, so every field is treated as untrusted.
func canonicalizeAssets(assets []Asset) error {
	seen := make(map[string]bool, len(assets))
	for index := range assets {
		asset := &assets[index]
		asset.Name = strings.TrimSpace(asset.Name)
		if !isPlainFileName(asset.Name) {
			return fmt.Errorf("分片名不安全: %q", asset.Name)
		}
		if seen[asset.Name] {
			return fmt.Errorf("分片名重复: %q", asset.Name)
		}
		seen[asset.Name] = true
		if asset.Size <= 0 || asset.Size > maxAssetBytes {
			return fmt.Errorf("分片 %s 声明的大小 %d 超出范围", asset.Name, asset.Size)
		}
		digest, err := normalizeDigest(asset.SHA256)
		if err != nil {
			return fmt.Errorf("分片 %s: %w", asset.Name, err)
		}
		asset.SHA256 = digest
		sources := asset.URLs[:0]
		for _, url := range asset.URLs {
			trimmed := strings.TrimSpace(url)
			if trimmed == "" {
				continue
			}
			// The manifest is the trust root for the download: its sha256 only
			// proves the bytes match the manifest, so the transport must not
			// downgrade below TLS — a http:// source would let anyone on the
			// path swap the payload for a self-consistent forgery. Loopback
			// http stays legal: tests and local mirrors listen there, and no
			// remote attacker can reach it.
			if !strings.HasPrefix(strings.ToLower(trimmed), "https://") && !isLoopbackSourceURL(trimmed) {
				return fmt.Errorf("分片 %s 的下载地址必须为 https: %q", asset.Name, trimmed)
			}
			sources = append(sources, trimmed)
		}
		if len(sources) == 0 {
			return fmt.Errorf("分片 %s 没有下载地址", asset.Name)
		}
		asset.URLs = sources
	}
	return nil
}

// isPlainFileName rejects anything that could escape the staging root once it
// is used as a file name. The manifest is remote input.
func isPlainFileName(name string) bool {
	if name == "" || name == "." || name == ".." {
		return false
	}
	if strings.ContainsAny(name, `/\:`) {
		return false
	}
	return filepath.Base(name) == name
}

// normalizeDigest accepts either hex case and returns the lower-case form,
// which is what sha256.Sum256 produces.
func normalizeDigest(digest string) (string, error) {
	trimmed := strings.ToLower(strings.TrimSpace(digest))
	if len(trimmed) != sha256.Size*2 {
		return "", fmt.Errorf("sha256 长度不是 %d 个字符", sha256.Size*2)
	}
	if _, err := hex.DecodeString(trimmed); err != nil {
		return "", fmt.Errorf("sha256 不是合法十六进制: %w", err)
	}
	return trimmed, nil
}

// isLoopbackSourceURL reports whether the URL points at this machine
// (http://127.0.0.1 / localhost / [::1]), the one case a non-https source is
// acceptable: tests and local mirrors listen there.
func isLoopbackSourceURL(raw string) bool {
	parsed, err := url.Parse(raw)
	if err != nil || parsed.Scheme != "http" {
		return false
	}
	host := parsed.Hostname()
	return host == "127.0.0.1" || host == "localhost" || host == "::1"
}
